examples/src/minimal_assistant.ts
It's not always necessary but improves reliability (e.g. SIP) and seems worth having in the default case.
=> Include waitForParticipant in minimal example

.changeset/chatty-pillows-cross.md, .changeset/config.json, .changeset/silver-nails-rush.md, .changeset/ten-donkeys-happen.md, agents/CHANGELOG.md, agents/package.json, examples/CHANGELOG.md, plugins/openai/CHANGELOG.md, plugins/openai/package.json
=> fix(ci): set changeset to public

package.json
This should fix the broken image at the top of https://docs.livekit.io/agents-js/
=> Copy README images when generating docs

.changeset/rude-planets-march.md, agents/package.json, examples/package.json, plugins/openai/package.json, pnpm-lock.yaml
=> Update everything to rtc 0.11.0

.changeset/breezy-actors-end.md
This is causing the changeset action to fail, preventing creation of a PR.
=> Remove livekit-agents-examples from changeset

.changeset/afraid-camels-push.md, agents/package.json, agents/src/ipc/proc_pool.ts, pnpm-lock.yaml
depends on https://github.com/livekit/ts-mutex/pull/1. run pnpm install once merged and pubbed to npmjs.com
=> fix(worker): make numIdleProcesses work

.changeset/shiny-pugs-fry.md, agents/src/index.ts, agents/src/llm/function_context.ts
This commit reverts 61899cde8c7fc19791d9d7d6a5ccabc2bb8f94dd.
=> fix(llm): fix Zod function calling in CJS

.changeset/khaki-pants-cry.md, agents/src/pipeline/agent_output.ts, agents/src/pipeline/agent_playout.ts, agents/src/pipeline/pipeline_agent.ts, agents/src/stt/index.ts, agents/src/stt/stream_adapter.ts, agents/src/tts/stream_adapter.ts, plugins/silero/src/vad.ts
also introduces compatibility with VPA
still draft because tts.StreamAdapter is broken on VPA
=> feat(stt): implement StreamAdapter

.changeset/nervous-cycles-laugh.md, agents/src/multimodal/multimodal_agent.ts, agents/src/transcription.ts
this changes the API for transcription forwarder a tiny bit as a stopgap in order to make this work. won't be necessary when the better transcription comes along, and eventually transcription v2.
fixes #164
=> feat(multimodal): add speech committed events

.changeset/serious-zoos-arrive.md, plugins/openai/src/realtime/api_proto.ts
https://platform.openai.com/docs/guides/realtime#voices
=> add new OpenAI realtime voices

.changeset/mighty-dogs-pull.md, plugins/silero/src/onnx_model.ts
=> fix(silero): Windows compat: correct file load

.changeset/rude-grapes-dress.md, agents/src/pipeline/pipeline_agent.ts
fixes: https://github.com/livekit/agents-js/issues/177
=> fix(agent): correct interruption logic in VoicePipelineAgent

.changeset/three-waves-shop.md, plugins/silero/src/vad.ts
fixes: https://github.com/livekit/agents-js/issues/182
=> chore(silero): allow partial VAD options

.changeset/config.json, .changeset/eight-carrots-notice.md, .changeset/mighty-dogs-pull.md, .changeset/rude-grapes-dress.md, .changeset/seven-bananas-share.md, .changeset/three-waves-shop.md, agents/CHANGELOG.md, agents/package.json, examples/package.json, plugins/deepgram/CHANGELOG.md, plugins/deepgram/package.json, plugins/elevenlabs/CHANGELOG.md, plugins/elevenlabs/package.json, plugins/openai/CHANGELOG.md, plugins/openai/package.json, plugins/silero/CHANGELOG.md, plugins/silero/package.json, pnpm-lock.yaml
this time trying not to set `workspace:^0`, seeing if that works
=> fix(ci): changeset bumping major, attempt 2

.changeset/brave-needles-boil.md, .github/workflows/build.yml, CONTRIBUTING.md, agents/src/job.ts, agents/src/worker.ts
\+ CI changes from `next`
**use a merge commit to merge this PR, not a squash!**
=> sync: merge attributes PR to`main`

.changeset/calm-ants-build.md, .changeset/few-schools-run.md, .changeset/sweet-papayas-complain.md, .github/workflows/test.yml, README.md, REUSE.toml, agents/src/tokenize/basic/basic.ts, agents/src/tokenize/basic/sentence.ts, agents/src/tokenize/tokenizer.test.ts, plugins/deepgram/package.json, plugins/deepgram/src/stt.test.ts, plugins/elevenlabs/package.json, plugins/elevenlabs/src/tts.test.ts, plugins/openai/package.json, plugins/openai/src/llm.test.ts, plugins/openai/src/llm.ts, plugins/openai/src/stt.test.ts, plugins/openai/src/tts.test.ts, plugins/test/.gitattributes, plugins/test/README.md, plugins/test/package.json, plugins/test/src/index.ts, plugins/test/src/llm.ts, plugins/test/src/long.wav, plugins/test/src/stt.ts, plugins/test/src/tts.ts, plugins/test/tsconfig.json, plugins/test/tsup.config.ts, pnpm-lock.yaml, vitest.workspace.ts
still missing #203 
use a merge commit!
=> chore(sync): merge next -> main for 0.5.1

.changeset/moody-poems-juggle.md, plugins/openai/src/models.ts
=> groq: add support for llama 3.3 70b

.changeset/few-games-destroy.md, agents/src/multimodal/multimodal_agent.ts
=> add(multimodal): emit user started speaking event

.changeset/eight-mugs-glow.md, plugins/openai/src/tts.ts
=> fix(tts): add missing crypto import to OpenAI tts

.changeset/khaki-ties-design.md, agents/src/pipeline/agent_output.ts, agents/src/pipeline/pipeline_agent.ts
exposes transcription text and lets it be retrieved by VPA. works well enough until proper chat/transcriptions are implemented with Data Streams
fixes #204
=> fix(pipeline): add transcription for AGENT_SPEECH_COMMITTED

.changeset/eight-mugs-glow.md, .changeset/khaki-ties-design.md, .changeset/moody-poems-juggle.md, agents/src/pipeline/agent_output.ts, agents/src/pipeline/pipeline_agent.ts, plugins/openai/src/models.ts, plugins/openai/src/tts.ts
=> chore(sync): prepare for 0.5.2

examples/package.json, examples/src/outbound.ts, examples/src/outbound_example.ts, pnpm-lock.yaml
The example @mike-r-mclaughlin[ asked me in Slack](https://livekit-users.slack.com/archives/C07FY8WHGPM/p1734649583404219?thread_ts=1734600163.136739&cid=C07FY8WHGPM) to add here!
First contribution here so let me know if any changes are needed :)
=> feat: Add outbound example

.changeset/happy-coins-drop.md, agents/CHANGELOG.md, agents/package.json, examples/package.json, examples/src/outbound.ts, plugins/deepgram/CHANGELOG.md, plugins/deepgram/package.json, plugins/elevenlabs/CHANGELOG.md, plugins/elevenlabs/package.json, plugins/openai/CHANGELOG.md, plugins/openai/package.json, plugins/openai/src/stt.ts, plugins/silero/CHANGELOG.md, plugins/silero/package.json, pnpm-lock.yaml
Hey there!
OpenAI's whisper model supports the option of supplying a [system prompt](https://platform.openai.com/docs/api-reference/audio/createTranscription#audio-createtranscription-prompt) when calling the transcription API.  
We make use of this feature heavily and adding support for it should be as simple as adding the two proposed line changes.
Let me know what needs to happen before this can be officially supported in Agents JS.
=> feat(openai): Add whisper prompt support to STT

.changeset/green-eagles-perform.md, plugins/elevenlabs/src/models.ts, plugins/elevenlabs/src/tts.ts
=> add eleven labs flash models

.changeset/wicked-rivers-brush.md
pointing to main and not next because it's just changesets
fixes #253
=> chore(changeset): add changesets for rtc-node bump

.changeset/fifty-ads-doubt.md, agents/src/pipeline/pipeline_agent.ts
=> fix(pipeline): double LLM replies

.changeset/kind-cherries-wave.md, agents/src/stt/stream_adapter.ts, agents/src/tokenize/token_stream.ts, plugins/openai/src/llm.ts
=> fix(stt): gracefully fail on StreamAdapter errors

.changeset/blue-colts-accept.md, agents/package.json, agents/src/multimodal/agent_playout.ts, agents/src/multimodal/multimodal_agent.ts, agents/src/pipeline/agent_output.ts, agents/src/pipeline/agent_playout.ts, agents/src/pipeline/human_input.ts, agents/src/pipeline/pipeline_agent.ts, agents/src/tokenize/basic/basic.ts, agents/src/tokenize/basic/index.ts, agents/src/transcription.ts, examples/package.json, plugins/cartesia/package.json, plugins/deepgram/package.json, plugins/elevenlabs/package.json, plugins/openai/package.json, plugins/silero/package.json, plugins/test/package.json, pnpm-lock.yaml
=> replace transcription forwarder with synchronizer

.changeset/neat-bulldogs-trade.md, plugins/silero/src/vad.ts
=> fix(silero): erroneous bits of audio at start

.changeset/brown-elephants-yawn.md, .changeset/eight-dolls-change.md, .changeset/lazy-wolves-give.md, .changeset/lovely-horses-eat.md, .changeset/neat-bulldogs-trade.md, .changeset/red-pillows-grow.md, agents/src/cli.ts, agents/src/ipc/inference_proc_lazy_main.ts, agents/src/ipc/job_proc_lazy_main.ts, agents/src/pipeline/agent_output.ts, plugins/openai/src/realtime/realtime_model.ts, plugins/silero/src/vad.ts
=> chore(bump): 0.7.1

plugins/neuphonic/CHANGELOG.md, plugins/neuphonic/README.md, plugins/neuphonic/api-extractor.json, plugins/neuphonic/package.json, plugins/neuphonic/src/index.ts, plugins/neuphonic/src/models.ts, plugins/neuphonic/src/tts.test.ts, plugins/neuphonic/src/tts.ts, plugins/neuphonic/tsconfig.json, plugins/neuphonic/tsup.config.ts, pnpm-lock.yaml, turbo.json
This PR implements Neuphonic: https://neuphonic.com/ a TTS provider (I am an engineer at Neuphonic).
**I have tested this locally** using the example in `examples/pipeline_voice_agent.ts` by swapping out `openai.TTS()` for `neuphonic.TTS()` and it works fine!
=> Implementation for Neuphonic TTS Plugin

agents/src/multimodal/agent_playout.ts
Fixes https://github.com/livekit/agents-js/issues/311#issuecomment-2734518910
=> Multimodal: Don't mark segment end if cancelled

.changeset/metal-keys-run.md, plugins/deepgram/src/stt.ts
=> fix(deepgram): add keyterm for nova-3-general

plugins/neuphonic/src/tts.ts
Implementation of this PR: https://github.com/livekit/agents/pull/1688 for the LiveKit TS package.
It changes the way Neuphonic reports when all the audio has been received, using a new signal from the server.
=> Utilised new stop signal from Neuphonic API for indicating when all audio has been receieved.

.changeset/spotty-shrimps-join.md, agents/src/cli.ts, agents/src/ipc/inference_proc_lazy_main.ts, agents/src/ipc/job_proc_lazy_main.ts
Helping debug autoscaling issues.
=> add log statements for SIGTERM or SIGINT

agents/package.json, agents/tsconfig.json, plugins/openai/tsconfig.json, pnpm-lock.yaml, tsconfig.json
this partly reverts changes from https://github.com/livekit/agents-js/pull/105 as the composite flag seems to mess with the declaration files not being emitted correctly
=> Fix tsconfig

.changeset/ten-parents-help.md, agents/package.json, pnpm-lock.yaml
=> Update Livekit SDK version

agents/src/voice/agent_session.ts, agents/src/voice/events.ts
Added boiler plate for agent state and user state.
=> Add agent/user state 

agents/src/voice/agent_session.ts, agents/src/voice/room_io.ts
Add basic support for audio output
=> Add basic audio output support

agents/src/voice/audio_recognition.ts
=> Only do EOU detection if not speaking

.changeset/smart-poems-attack.md, agents/package.json, agents/src/ipc/inference_proc_executor.ts, agents/src/ipc/job_proc_executor.ts, package.json, plugins/cartesia/package.json, plugins/deepgram/package.json, plugins/elevenlabs/package.json, plugins/livekit/package.json, plugins/livekit/src/index.ts, plugins/neuphonic/package.json, plugins/openai/package.json, plugins/resemble/package.json, plugins/silero/package.json, plugins/test/package.json, pnpm-lock.yaml, scripts/copyDeclarationOutput.js, tsup.config.ts
in order to properly support cjs imports in typescript. 
confirmed approach with publint.dev
=> fix: avoid masquerading types as mjs

plugins/assemblyai/CHANGELOG.md, plugins/assemblyai/README.md, plugins/assemblyai/api-extractor.json, plugins/assemblyai/package.json, plugins/assemblyai/src/index.ts, plugins/assemblyai/src/stt.test.ts, plugins/assemblyai/src/stt.ts, plugins/assemblyai/tsconfig.json, plugins/assemblyai/tsup.config.ts, pnpm-lock.yaml, turbo.json
Taking over PR from https://github.com/livekit/agents-js/pull/315
=> Shubhra/AssemblyAI Plugin 

.github/workflows/test.yml
=> Add Assembly AI API key to Github Action

.changeset/cuddly-papayas-explode.md, agents/src/http_server.ts, agents/src/worker.ts
=> Add sdk version to worker endpoint

.changeset/cold-tomatoes-eat.md, agents/src/llm/llm.ts, agents/src/tts/tts.ts
Same as the python implementation 
- [TTS](https://github.com/livekit/agents/blob/76b2d7f39c744665b86b89e02bd789d23d907707/livekit-agents/livekit/agents/tts/tts.py#L163)
- [LLM](https://github.com/livekit/agents/blob/76b2d7f39c744665b86b89e02bd789d23d907707/livekit-agents/livekit/agents/llm/llm.py#L197)
=> Shubhra/set ttft and ttfb to -1 when queue is empty

plugins/silero/src/vad.ts
=> bugifx in VAD

.changeset/tall-months-doubt.md, plugins/silero/src/vad.ts
=> Fix bug with speech duration calculation

agents/src/voice/agent.ts, agents/src/voice/agent_activity.ts
A little clearer to users it's internal use only.
=> Prefix agentActivity with _

agents/src/voice/agent.ts, agents/src/voice/agent_activity.ts, agents/src/voice/generation.ts, agents/src/voice/io.ts
Setting up this [python object](https://github.com/livekit/agents/blob/74fdb91c2f81c7d75e5b48acb53bb54562d7cb5f/livekit-agents/livekit/agents/voice/agent.py#L21-L24)
=> Add ModelSettings

agents/src/voice/room_io/room_io.ts
Need to make event listener an arrow function
=> Shubhra/bugfix with `this` binding

agents/src/voice/room_io/room_io.ts, examples/src/basic_agent.ts, examples/src/basic_tool_call_agent.ts, examples/src/push_to_talk.ts, examples/src/restaurant_agent.ts
This reverts commit 1636b99778050d1cc1f8ce4b8ebf936cc28c412d.
=> Revert Audio Input Stream

agents/src/llm/index.ts, agents/src/llm/realtime.ts, agents/src/voice/agent_activity.ts
Wire up the realtime session event listers in `AgentActivity`
=> Shubhra/ Add realtime event listeners in AgentActivity

plugins/openai/src/llm.ts
=> Revert "Fix Tool Parsing to Allow Object Return Value"

.changeset/olive-ears-live.md, plugins/openai/src/llm.ts
=> Remove double stringify for string tool result

.github/pull_request_template.md
=> Create a PR Template

agents/src/voice/agent_activity.ts, agents/src/voice/events.ts
Made in a separate PR so it's easier to review. All the other events are added in https://github.com/livekit/agents-js/pull/551
=> Add agent session events for function calls

agents/src/voice/room_io/room_io.ts
We still need to support text inputs. Made a ticket for it.
=> Shubhra/AJS 135 Toggle Room IO based on user options

agents/src/llm/utils.test.ts, agents/src/llm/utils.ts
=> Support all types of VideoFrames to LLM Multimodal Inference

README.md
Update README accordingly to python agents
=> Update 1.0 Readme

.changeset/cyan-baths-wait.md, README.md, examples/package.json, examples/src/comprehensive_test.ts, plugins/google/src/llm.ts, plugins/openai/src/realtime/realtime_model.ts, pnpm-lock.yaml
Add a comprehensive test and fix google plugins
=> Comprehensive example and bug fixes with google plugins

.changeset/social-suns-count.md, agents/src/voice/audio_recognition.ts
Fix audio recognition setting sample rate
=> Fix sample rate in audio recogntion

README.md
=> Fix readme header

.changeset/twelve-groups-visit.md, agents/src/ipc/job_proc_lazy_main.ts
We were not calling the function
=> Shubhra/fix UUID for inference proc

agents/src/utils.ts
Utils for writing data stream audio output component
=> Add DataStreamAudioOutput Utils

.changeset/stupid-maps-stare.md, agents/src/voice/agent_activity.ts, agents/src/voice/events.ts
Add language field to `UserInputTranscribed` Event
=> Add language to UserInputTranscribed event

agents/src/voice/speech_handle.ts
We were not actually waiting for the speech handle.
=> Bugfix - actually wait for playout in speech handle. 
