livekit/agents-js

.changeset/ten-donkeys-happen.md
agents/src/ipc/job_main.ts

fixes the usage on windows where importing with paths doesn't automatically map it on top of a URL
closes #94

fix(job_main): import using URLs, not paths

---

plugins/openai/package.json
plugins/openai/src/realtime/realtime_model.ts
plugins/openai/tsconfig.json
tsconfig.json

This PR resolves type errors below.
```sh
$ pnpm build
> @livekit/agents-plugin-openai@0.3.2 build /Users/ocean/contrib/agents-js/plugins/openai
> tsc
src/realtime/realtime_model.ts:4:73 - error TS2307: Cannot find module '@livekit/agents' or its corresponding type declarations.
4 import { AsyncIterableQueue, Future, Queue, llm, log, multimodal } from '@livekit/agents';
~~~~~~~~~~~~~~~~~
src/realtime/realtime_model.ts:425:24 - error TS18046: 'func' is of type 'unknown'.
425           description: func.description,
~~~~
src/realtime/realtime_model.ts:426:37 - error TS18046: 'func' is of type 'unknown'.
426           parameters: llm.oaiParams(func.parameters),
~~~~
src/realtime/realtime_model.ts:621:10 - error TS2339: Property 'emit' does not exist on type 'RealtimeSession'.
621 …
```

build(openai): paths mapping and composite

---

.changeset/silver-nails-rush.md
agents/src/multimodal/multimodal_agent.ts

Agent fails to subscribe to user track if it was connect to room before agent.

Fix subscription timing

---

.changeset/chatty-pillows-cross.md
examples/src/minimal_assistant.ts
plugins/openai/src/realtime/api_proto.ts
plugins/openai/src/realtime/realtime_model.ts
turbo.json

Ported from Python PR: https://github.com/livekit/agents/pull/848

Support for Azure OpenAI Realtime

---

package.json

Unfortunately #116  didn't work both due to a leading slash in the img tag (which means relative to the host not the current path) and due to the .github/ folder not being exposed from S3/cloudfront. Instead of making changes in readme manager, I changed the doc gen script to also rewrite the image url and move the images into assets where they belong.

Move github banners to assets directory

---

.changeset/breezy-actors-end.md
agents/package.json
examples/package.json
plugins/openai/package.json
pnpm-lock.yaml

a new version of rtc-node is incompatible with previous releases, and will lead to Rust panics if two or more differing versions are used between packages:
```
thread '<unnamed>' panicked at src/nodejs.rs:52:13:
failed to handle request: invalid request: handle not found
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
thread '<unnamed>' panicked at library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind
```
this patch updates agents repositories to the latest version of rtc-node, so it should be okay to use the latest available version on your end as well.
if for some reason you can't update agents, pin the version of `@livekit/rtc-node` to `=0.9.0`.

fix(treewide): use newer rtc-node version

---

examples/src/minimal_assistant.ts

This aligns the format more closely with the one added to the docs in https://github.com/livekit/web/pull/541, which in turn is more consistent with the python implementation.

Break function calling out in example to be clearer

---

.changeset/breezy-pandas-compare.md
agents/src/multimodal/multimodal_agent.ts

There's an error in the console every time about "Participant is not set" when this runs before the participant gets linked. The whole thing is unnecessary - we don't need to lookup the publications again, we just need to subscribe to mic tracks if the linked participant publishes one.

Subscribe to published mic track for linked participant only

---

.changeset/purple-beds-clean.md
agents/src/llm/chat_context.ts
agents/src/llm/function_context.ts
agents/src/llm/index.ts
agents/src/multimodal/multimodal_agent.ts
examples/src/minimal_assistant.ts
plugins/openai/src/realtime/realtime_model.ts

incomplete implementation, notably missing tool call hooks (see comment
for more info).

feat(llm): add ChatContext 

---

plugins/openai/src/realtime/realtime_model.ts

Include usage (number of input/output tokens) in the `response_done` event.

add usage to the response_done event

---

.changeset/forty-bulldogs-shop.md
agents/src/llm/function_context.test.ts
agents/src/llm/function_context.ts
plugins/openai/src/realtime/api_proto.ts

this PR
* updates oaiParams to include the items property in arrays to match openAI's function call schema requirements (fixes issue https://github.com/livekit/agents-js/issues/124)
* updates oaiParams to omit optional fields from the required section of the generated openAI function call schema
* adds unit tests for oaiParams

support arrays and optional fields in function call schema

---

.changeset/plenty-fans-kiss.md
agents/src/index.ts

there's a weird edge-case with `tsx` where if `module` is unset in package.json but the typescript file still uses module imports, it will still run, but as CommonJS, without checking for inconsistencies. this doesn't immediately break agents, instead erroring on `job_main.js`, without throwing a useful error.
we do not support and have not supported CommonJS, this PR just throws an error for this specific usecase which has thrown a few folks for a loop.
for reference, compiling to JavaScript and then running with those settings throws an explicit error on Node's side before ever reaching index.js.

chore(agents): explicitly unsupport CommonJS

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

@davidzhao add conduct@ email alias, and merge

Add contribution guide and a code of conduct

---

.changeset/small-roses-flow.md
.github/workflows/release.yml

silero vad is broken currently on npm because the LFS file wasn't pulled

chore(ci): enable LFS in publish script

---

.changeset/config.json

this should stop packages from all keeping the same version number and updating all when one plugin is bumped

chore(ci): remove "fixed" from changesets config

---

plugins/openai/src/realtime/api_proto.ts
plugins/openai/src/realtime/realtime_model.ts

Improve the `usage` attribute of `ResponseUsage`, now defined in its own type `ModelUsage`.  
With OpenAI Realtime API, there are 6 different token types, all with different prices.  The data is already present at runtime but not expressed in livekit's typings.

add fully defined ModelUsage type

---

.changeset/seven-dryers-repeat.md
plugins/openai/src/realtime/realtime_model.ts

This adds simple support for reading the responses of a text-only Realtime API Model. I found no way currently to get the responses as transcriptions don't seem to be created when only the "text" modality is chosen. 
In our case, we patched these changes and forwarded the text to the agent's publication track so our client handles audio and text transcriptions the same way.

feat(openai): emit Realtime API response text delta and done

---

.changeset/two-shirts-cover.md
agents/src/llm/function_context.ts
plugins/openai/src/llm.ts
plugins/openai/src/realtime/realtime_model.ts

this is less brittle (in case openai updates its schema for parameters, you can edit without waiting for us to fix), but doesn't supply the type reinforcements with Zod.

feat(openai): allow raw JSON function parameters

---

.changeset/fifty-apes-whisper.md
plugins/elevenlabs/src/tts.ts

Providing any `opts` to `elevenlabs.TTS` without the `apiKey` will result in an error since we are only merging the `opts` with the defaults after the check
ex.
```ts
// Will throw an error since an apiKey isn't provided and the defaults with the env variable isn't provided
elevenlabs.TTS({}) 
```
* Set and merge `#opts` with defaults before `apiKey` check
* Remove defaulting `opts` argument to `defaultTTSOptions` since its technically not needed

fix(elevenlabs): override with defaults if opts are provided

---

.changeset/calm-wolves-mate.md
agents/src/pipeline/pipeline_agent.ts

When converting the LLM stream response to string, `choices[0]` could potentially be `undefined`
* Add in optional chain check on `choices[0]`
* ***Note*** Was testing on a local agent
* Respond to agent via voice
* When a response was returned from the LLM, `choices[0]` was undefined
* Enabling [noUncheckedIndexedAccess](https://www.typescriptlang.org/tsconfig/#noUncheckedIndexedAccess) would prevent this issue moving forward

fix(agent): ensure safe access of conversation content

---

.changeset/itchy-sheep-smash.md
agents/src/tokenize/token_stream.ts
plugins/elevenlabs/src/tts.ts

Was noticing the last word for TTS was not being outputted (Websocket, ElevenLabs).
The input stream was not being flushed, and therefore, the remaining token was not being sent upstream.
* Ensure `BufferedTokenStream` ends the input and is flushed before closing
* Implement missing wrapping methods for `BufferedWordStream` so the underlying `WordStream` implementations isn't used
* Use voice agent pipeline with ElevenLabs
* Every spoken prompt would be missing the last word
* `WordStream` can probably be converted to an interface since the underlying implementation is technically not needed

fix(agent): ensure token stream flushes

---

.changeset/clean-pugs-lick.md
agents/src/ipc/job_main.ts
agents/src/ipc/proc_job_executor.ts
agents/src/job.ts
agents/src/llm/function_context.ts
agents/src/pipeline/pipeline_agent.ts
agents/src/stt/stream_adapter.ts
agents/src/stt/stt.ts
agents/src/tokenize/basic/hyphenator.ts
agents/src/utils.ts
agents/src/worker.ts
examples/src/stt.ts
plugins/deepgram/src/stt.ts
plugins/openai/src/realtime/realtime_model.ts
plugins/silero/src/onnx_model.ts
tsconfig.json

used `!` for places where we either check earlier, or we know for absolutely certain that there's gonna be a value.

chore(tsconfig): enable `noUncheckedIndexedAccess`

---

.changeset/slimy-hounds-decide.md
.changeset/swift-mails-beg.md
agents/src/pipeline/pipeline_agent.ts

The voice pipeline agent's state attribute is called `"ATTRIBUTE_AGENT_STATE"`. Other LiveKit SDKs (e.g. [JS SDK multimodal agent](https://github.com/livekit/agents-js/blob/9734c34ba3d4b6961042cdeee25be3680a548f4f/agents/src/multimodal/multimodal_agent.ts#L55), [Python agents SDK](https://github.com/livekit/agents/blob/70b4e87f592d34785ebc7b4cc6badefce5291197/livekit-agents/livekit/agents/types.py#L5), [React SDK](https://github.com/livekit/components-js/blob/92e2c1733f91b218e0a7a95da6934f97d981bee5/packages/react/src/hooks/useVoiceAssistant.ts#L33)) expect the attribute to be called `"lk.agent.state"`, meaning that the agent state is not picked up correctly by other LiveKit clients, such as my frontend.
This PR defines the correct attribute name as a constant, and sets the agent state on …

fix(vpa): correct state attribute name

---

README.md
examples/package.json
package.json

The file `minimal_assistant.ts` was renamed to `multimodal_agent.ts` in #138, but there were still references to the old name.

Fix old references to minimal_assistant.ts in examples

---

.changeset/config.json

after this is merged, new branch `stable` will be created, and `main` will be renamed `next`. all development will take place on `next`, with occasional cherry-picks of relevant commits in PRs to `stable`, after which we cut new releases.
https://www.notion.so/livekit/the-stable-next-repository-model-14d3c4901a428099bc7cccfda8e1fa8b?pvs=4

ci: change changelogs main branch to stable

---

.changeset/few-schools-run.md
agents/src/tokenize/basic/sentence.ts
agents/src/tokenize/tokenizer.test.ts

while writing this patch, i found that using `bun test` instead of vitest is much _much_ (up to 100x) faster. i know we don't explicitly target Bun but it might be worth using it in our CI for testing instead of vitest, especially with later integration tests.

test(tokenizer): add tests + fix tokenizer

---

.changeset/hot-otters-pay.md
agents/src/pipeline/index.ts
agents/src/pipeline/pipeline_agent.ts
agents/src/pipeline/speech_handle.ts

```js
await pipeline.AgentCallContext.getCurrent().agent.say("foobar", true);
```

feat(pipeline): nested speech handles

---

.changeset/clean-lies-grow.md
agents/src/multimodal/multimodal_agent.ts

removed the janky half-implementation of cancellations that didn't work and caused the agent to error out when reconnecting to the same room.
fixes #214

fix(multimodal): crash on reconnect to same room

---

.github/workflows/test.yml

run all tests if tests or agents are changed, otherwise run only relevant plugin tests.

test: run conditional tests only for changed files

---

.changeset/afraid-camels-listen.md
agents/src/ipc/proc_job_executor.ts

we see a lot of bug reports focusing on ERR_IPC_CHANNEL_CLOSED, because it is the *big scary exception*, when in reality the actual error gets logged a few lines up. this gets rid of the useless log and should hopefully lead to more useful bug reports

fix(proc): clearer errors on crash

---

.changeset/clean-garlics-cross.md
agents/src/ipc/proc_job_executor.ts
agents/src/metrics/base.ts

we don't use ErrorOptions in any of our other `extends Error`s, and this causes a misbuild on some targets, presumably because of TS targets and modules.

fix(metrics): fix MultimodalLLMError typescript

---

.changeset/late-buckets-draw.md
plugins/silero/src/vad.ts

Implementation of `updateOptions` function on Silero VAD (Issue #268).
I Took heavy inspiration for this from the [python implementation](https://github.com/livekit/agents/blob/695f7b567d0b7fffa6a18f14c74e50421434a0aa/livekit-plugins/livekit-plugins-silero/livekit/plugins/silero/vad.py#L217), though I did not look too deep at the differences between `#task` and `_main_task`, so there may be implications I am not aware of.

feat(silero): update options for Silero VAD

---

.changeset/odd-turkeys-boil.md
plugins/deepgram/src/stt.ts

Deepgram has lots of feature which are helpful for speech to text
https://developers.deepgram.com/docs/stt-streaming-feature-overview
Below feature are missing in Deepgram STT plugin
Dictation : https://developers.deepgram.com/docs/dictation
Numerals : https://developers.deepgram.com/docs/numerals
Diarization: https://developers.deepgram.com/docs/diarization
https://github.com/livekit/agents-js/issues/294

feat(deepgram): missing STT options

---

.changeset/rude-fireants-return.md
agents/src/tokenize/token_stream.ts
plugins/openai/src/llm.ts

drive-by fixes some hacky array checks in tokenizer.
fixes #233 (one of the issues on there)

fix(openai): null LLM input

---

.changeset/lazy-horses-divide.md
agents/src/pipeline/agent_output.ts

1. In some cases, an LLM plugin can generate a blank ("") string when outputting a response. One example of this is when the OpenAI LLM plugin generates a tool function execution request.
2. If there is no text, some streaming TTS plugins, the Cartesia plugin for example, will not generate any audio.
3. If no audio is generated, then the for await call in the readGeneratedAudio function in agent_output.ts will never loop and the handle.queue.put(SynthesisHandle.FLUSH_SENTINEL); function will never be called. In this case the pipeline agent will go into an infinite wait loop because it is awaiting for a signal that the audio queue can be flushed, but it never happens.
4. We fix this by explicitly calling handle.queue.put(SynthesisHandle.FLUSH_SENTINEL); in cases where the string is missing …

Fixes infinte await in agent_output.ts

---

plugins/openai/src/realtime/realtime_model.ts

It's using `2024-10-01-preview` hardcoded value without chance to change apiVersion.
In [Azure document](https://learn.microsoft.com/en-us/azure/ai-services/openai/realtime-audio-quickstart?tabs=keyless%2Clinux&pivots=programming-language-typescript), it is stated that: "Use the latest `2024-12-17` model version".

Use #opts.apiVersion

---

.changeset/gentle-jokes-refuse.md
agents/src/multimodal/agent_playout.ts

replaces https://github.com/livekit/agents-js/pull/317
when `queuedDuration` is bigger than `pushedDuration`, audioSamples can become negative

fix(multimodal): ensure audio samples is never smaller than 0

---

.changeset/eight-dolls-change.md
agents/src/ipc/job_proc_lazy_main.ts

this way whole processes don't exit whenever something errored, instead attempting to continue

log unhandled promise rejections

---

.changeset/lazy-wolves-give.md
agents/src/pipeline/agent_output.ts

fix(pipeline): don't mark segment end if cancelled

---

.changeset/fix-synchronizer-race.md
agents/src/multimodal/agent_playout.ts

The race condition occurs because the `TextAudioSynchronizer` is closed before the readText task is cancelled. When the readText task continues running and calls methods on the already-closed synchronizer, it triggers the "TextAudioSynchronizer is closed" error. This fix ensures all tasks are properly cancelled before closing the synchronizer.

fix: resolve race condition in TextAudioSynchronizer closure

---

plugins/neuphonic/src/tts.test.ts
plugins/test/src/tts.ts

Testing flow is as follows. 
Take sample text -> Convert to audio (with TTS) -> Convert back to text (STT) -> make sure that it's similar to the first text.
The sample test we had was taking around 12-15 seconds for TTS and then another 12-15 seconds for STT. This was causing our tests to time out. 
I updated the text to be smaller. Don't really see a need for the text to be so long.

Fix tts tests timing out

---

.changeset/noise-cancellation.md
agents/package.json
agents/src/multimodal/multimodal_agent.ts
agents/src/pipeline/human_input.ts
agents/src/pipeline/pipeline_agent.ts
pnpm-lock.yaml

- For VoicePipelineAgent: Added to VPAOptions interface
- For MultimodalAgent: Added as constructor parameter
Regarding the implementation for MultimodalAgent, I've currently added an extra parameter to the constructor, but I believe this isn't the best approach. Similar to how we added `AudioStreamOptions` to `AudioStream`, I think it would be better to create a parameter that consolidates options.
However, since I lack context on this project, I'd appreciate your opinion on how to best structure this.

Add noise cancellation support to VoicePipelineAgent and MultimodalAgent

---

examples/package.json
plugins/cartesia/package.json
plugins/deepgram/package.json
plugins/elevenlabs/package.json
plugins/neuphonic/package.json
plugins/openai/package.json
plugins/resemble/package.json
plugins/silero/package.json
plugins/test/package.json
pnpm-lock.yaml

Solved these errors I was getting. 
```
objc[89885]: Class RTCVideoCodecInfo is implemented in both /Users/shubhrakantiganguly/development/agents-js/node_modules/.pnpm/@livekit+rtc-node-darwin-arm64@0.13.11/node_modules/@livekit/rtc-node-darwin-arm64/rtc-node.darwin-arm64.node (0x11f4a0050) and /Users/shubhrakantiganguly/development/agents-js/node_modules/.pnpm/@livekit+rtc-node-darwin-arm64@0.13.4/node_modules/@livekit/rtc-node-darwin-arm64/rtc-node.darwin-arm64.node (0x125100038). One of the two will be used. Which one is undefined.
objc[89885]: Class RTCEncodedImage is implemented in both /Users/shubhrakantiganguly/development/agents-js/node_modules/.pnpm/@livekit+rtc-node-darwin-arm64@0.13.11/node_modules/@livekit/rtc-node-darwin-arm64/rtc-node.darwin-arm64.node (0x11f4a00c8) and …
```

Update version for livekit rtc

---

.changeset/good-papayas-crash.md
agents/src/audio.ts
agents/src/pipeline/agent_playout.ts

Allow the agent playout to be buffered. Previously we were waiting every Frame to be acknowledged by the FFiclient before we queued the next one.

Fix frame size from TTS output and bug where we don't queue frames

---

.changeset/tall-apes-hug.md
agents/src/job.ts

this is technically not a bug, just a weird thing that JavaScript does, where getters aren't shown on `console.log()`, so it looks like the object is empty. this PR just sets them statically as readonly.
closes #346

refactor(job): show job request attrs on print

---

.changeset/heavy-cats-unite.md
agents/src/constants.ts
agents/src/multimodal/multimodal_agent.ts
agents/src/pipeline/pipeline_agent.ts

depends on https://github.com/livekit/node-sdks/pull/447
add support for text stream based transcriptions while trying to leave things as they are otherwise. 
The whole synchronizer logic (esp. wrt to deltas) should get an overhaul for 1.0 as a bunch of things changed on the python side.

Publish transcriptions additionally via text stream APIs

---

.eslintrc
agents/src/voice/agent_session.ts
agents/src/voice/generation.ts
agents/src/voice/io.ts
agents/src/voice/room_io/_output.ts

Pulling up `TextOutput` and `AudioOutput` into public interfaces users can inherit. This will also make Future PRs easier to read since we already define the base classes.
**There are not functional changes in this PR**

Pull up `TextOutput` and `AudioOutput` into abstract classes users can inherit. 

---

agents/src/llm/provider_format/openai.test.ts
agents/src/llm/provider_format/utils.ts

Fix message ordering in `ChatContext` to `ChatItemGroup` conversion
Ensure messages are ordered by their group creation sequence instead of by randomly generated UUIDs. This resolves incorrect message ordering during conversion.
Reference: https://live-kit.slack.com/archives/C07TWVC0W4A/p1750106401327539

Fix Chat Messages Ordering

---

.github/workflows/test.yml

https://github.com/livekit/agents-js/pull/448 missed adding an API key to one of the configs. This error was muted because tests weren't running on the PRs when `workflow` files were edited.

Run test on PRs with changes in workflow files

---

agents/src/tts/tts.ts
agents/src/utils.test.ts
agents/src/utils.ts
agents/src/voice/agent.ts
agents/src/voice/agent_activity.ts
agents/src/voice/generation.ts
examples/src/basic_tool_call_agent.ts
examples/src/push_to_talk.ts

Issue is that when perform tool calling, the text stream will be a empty stream. This won't trigger `pushText` method in ts's `SynthesizeStream` object. However, pushText lazily starts `monitorMetrics` task, which controlling the close lifecycle stage of the tts stream. Without any text chunk, we cannot start `monitorMetrics` which make the TTS stream unable to close so it become hanging. 
This PR separate the close outside of monitorMetric task so it call `this.output.close()` as soon as the main task finishes

Fix TTS Hanging when Receiving empty text stream

---

agents/src/voice/room_io/room_io.ts

Just needed to expose it to the `Room.start` api

Add noise cancellation option to agent start

---

.changeset/heavy-cherries-yell.md
agents/src/constants.ts
agents/src/multimodal/multimodal_agent.ts
agents/src/pipeline/pipeline_agent.ts

The python agents sdk includes a `lk.segment_id` attribute in all transcription events, which clients ([js sdk example](https://github.com/livekit/components-js/blob/6f02e9f9b3e7737863d256b26a26ade914a5066a/packages/core/src/components/textStream.ts#L79-L85)) can use to deduplicate non finalized events into a list of renderable transcription messages.
However, the agents-js sdk doesn't include this field, and because the `id` field for human-generated transcriptions isn't always the same for transcriptions that represent the same speech, there's no way for that deduplication to occur, which at least in [agents-starter-react](https://github.com/livekit-examples/agent-starter-react) results in rendering each partial transcription distinctly in lists, which is bad:
So, to address this, this …

Send `lk.segment_id` attribute in transcription events so non final transcriptions can be deduplicated client side

---

.changeset/bright-cups-type.md
plugins/livekit/package.json
plugins/silero/package.json
pnpm-lock.yaml

There's [a bug in 1.22.0](https://github.com/microsoft/onnxruntime/issues/24770) that breaks the install on linux, such as in cloud agents. Since this is the latest version it means new node projects currently break on deploy to cloud agents if they use silero or turn detector.
They did publish a 1.22.0-rev that is supposed to fix it but I can't get it to reliably fix the issue, so I think the better immediate course of action is to just stick to 1.21.0 for now and we can later update to 1.23.0+

Don't support onnxruntime 1.22.0

---

.changeset/dry-states-smile.md
agents/src/inference/llm.ts

Add a temporary placeholder key in OpenAI client SDK, preventing it to complain when using inference gateway

Allow Not Specify OPENAI_API_KEY when using Inference Gateway

---

.changeset/young-dryers-give.md
plugins/rime/README.md

1.0.0 was marked as deprecated before so release CI failed when attempting to publish the same version. Unblock the release by making it start with 1.0.1

Patch Rime TTS Plugin
